# Generated by Django 5.1 on 2024-08-26 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('latest_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pl_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rebalance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('SGD', 'Singapore Dollar'), ('NZD', 'New Zealand Dollar'), ('HKD', 'Hong Kong Dollar'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso')], default='USD', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='investments.portfolio')),
            ],
        ),
    ]
